version: "3.9"
services:
  sql-database:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "${DB_PORT:-1433}:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_TCP_PORT: 1433
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
