version: "3.9"
services:
  sql-database:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Ttaarreekk/93"
      MSSQL_TCP_PORT: 1433
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
